--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.894.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04.10.2022 17:47:54
-- Server version: 8.0.30
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO world_skills.competition_skill(competition_id, skill_id) VALUES
(1, 0),
(1, 31),
(1, 52),
(1, 53),
(1, 55),
(1, 77),
(1, 79),
(1, 88),
(2, 0),
(2, 52),
(2, 55),
(2, 77),
(2, 88),
(2, 94),
(3, 0),
(3, 52),
(3, 79),
(3, 88),
(4, 0),
(4, 1),
(4, 2),
(4, 3),
(4, 4),
(4, 5),
(4, 6),
(4, 7),
(4, 10),
(4, 15),
(4, 16),
(4, 24),
(4, 31),
(4, 32),
(4, 33),
(4, 34),
(4, 35),
(4, 36),
(4, 41),
(4, 42),
(4, 43),
(4, 44),
(4, 45),
(4, 46),
(4, 47),
(4, 48),
(4, 49),
(4, 50),
(4, 51),
(4, 52),
(4, 53),
(4, 54);