--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.894.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04.10.2022 17:47:54
-- Server version: 8.0.30
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO world_skills.role(id, role) VALUES
(1, 'Участник'),
(2, 'Эксперт'),
(3, 'Гланый эксперт'),
(4, 'Заместитель главного эксперта'),
(5, 'Технический эксперт'),
(6, 'Организатор');