--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.894.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04.10.2022 17:47:54
-- Server version: 8.0.30
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO world_skills.skill_block(id, title) VALUES
(1, 'Информационные и коммуникационные технологии'),
(2, 'Образование'),
(3, 'Производство и инженерные технологии'),
(4, 'Строительство и строительные технологии'),
(5, 'Сфера услуг'),
(6, 'Творчество и дизайн'),
(7, 'Транспорт и логистика'),
(8, 'Future Skills');